name: Default

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_modified_files:
    name: Check modified files
    runs on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: check-files
        with:
          filter: |
            backend_modified:
              - 'backend/**'
              - pyproject.toml
              - poetry.lock
    outputs:
      backend_modified: ${{ steps.check-files.outputs.backend_modified }}

  backend_tests:
    name: Guardian Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Poetry Install
        run: pip install poetry==1.3.2

      - uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
          cache: poetry

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          poetry install --no-root --no-interaction

      - name: Run style guide, linter and typing checks
        working-directory: ${{ github.workspace }}
        run: |
          source $(poetry env info --path)/bin/activate
          flake8 backend
